spring.application.name=auth-service

server.port=4005

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

logging.level.com.pms.authservice=DEBUG

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Event publisher: "kafka" or unset (defaults to logging publisher)
# registration.event.publisher=kafka
