services:
  # Kafka Broker
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - internal

  # PostgreSQL for patient-service
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5000:5432"
    volumes:
      - ./patient-service/patient-service-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # Patient Service
  patient-service:
    image: patient-service:latest
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    container_name: patient-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      GRPC_SERVER_PORT: 9000
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      patient-service-db:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - internal

  # Billing Service
  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal

  # Analytics Service
  analytics-service:
    image: analytics-service:latest
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    container_name: analytics-service
    ports:
      - "4002:4002"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_started
    networks:
      - internal

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "4004:4004"
    networks:
      - internal

  #Auth service db
  auth-service-db:
    image: postgres:latest
    container_name: auth-service-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5001:5432"
    volumes:
      - ./auth-service/auth-service-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  auth-service:
    image: auth-service:latest
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      JWT_SECRET: dGhpc0lzQVZlcnlTZWN1cmVTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb24xMjM0NTY3OA==
      HOSPITAL_SERVICE_GRPC_HOST: hospital-service
      HOSPITAL_SERVICE_GRPC_PORT: 9003
      PATIENT_SERVICE_GRPC_HOST: patient-service
      PATIENT_SERVICE_GRPC_PORT: 9000
    depends_on:
      auth-service-db:
        condition: service_healthy
    networks:
      - internal

  # PostgreSQL for hospital-service
  hospital-service-db:
    image: postgres:latest
    container_name: hospital-service-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5002:5432"
    volumes:
      - ./hospital-service/hospital-service-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # Hospital Service
  hospital-service:
    image: hospital-service:latest
    build:
      context: ./hospital-service
      dockerfile: Dockerfile
    container_name: hospital-service
    ports:
      - "4003:4003"
      - "9003:9003"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://hospital-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    depends_on:
      hospital-service-db:
        condition: service_healthy
    networks:
      - internal

  # PostgreSQL for clinical-service
  clinical-service-db:
    image: postgres:latest
    container_name: clinical-service-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5004:5432"
    volumes:
      - ./clinical-service/clinical-service-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # Clinical Service
  clinical-service:
    image: clinical-service:latest
    build:
      context: ./clinical-service
      dockerfile: Dockerfile
    container_name: clinical-service
    ports:
      - "4010:4010"
    volumes:
      - ./clinical-service/pdf-storage:/app/pdf-storage
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://clinical-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    depends_on:
      clinical-service-db:
        condition: service_healthy
    networks:
      - internal

  # PostgreSQL for schedule-service
  schedule-service-db:
    image: postgres:latest
    container_name: schedule-service-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5003:5432"
    volumes:
      - ./schedule-service/schedule-service-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # Schedule Service
  schedule-service:
    image: schedule-service:latest
    build:
      context: ./schedule-service
      dockerfile: Dockerfile
    container_name: schedule-service
    ports:
      - "4009:4009"
      - "9009:9009"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://schedule-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      schedule-service-db:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - internal

networks:
  internal:
    external: true
