services:
  # Kafka Broker
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - internal

  # Redis (shared — OTP TTLs, dedup keys, rate limit counters)
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - internal

  # PostgreSQL for patient-service
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5000:5432"
    volumes:
      - ./patient-service/patient-service-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # Patient Service
  patient-service:
    image: patient-service:latest
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    container_name: patient-service
    ports:
      - "4000:4000"
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      GRPC_SERVER_PORT: 9000
      # gRPC client uses discovery:/// via Eureka — no static host/port needed
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      patient-service-db:
        condition: service_healthy
      kafka:
        condition: service_started
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:5000"
    networks:
      - internal

  # Billing Service
  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    depends_on:
      kafka:
        condition: service_started
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:5000"
    networks:
      - internal

  # Analytics Service
  analytics-service:
    image: analytics-service:latest
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    container_name: analytics-service
    ports:
      - "4002:4002"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_started
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:5000"
    networks:
      - internal

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "4004:4004"
    depends_on:
      auth-service:
        condition: service_started
      hospital-service:
        condition: service_started
      patient-service:
        condition: service_started
      clinical-service:
        condition: service_started
      schedule-service:
        condition: service_started
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:5000"
    networks:
      - internal

  #eureka server
  eureka-server:
    image: eureka-server:latest
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:password@eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://eureka:password@eureka-server:8761/eureka/apps"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - internal

  #Auth service db
  auth-service-db:
    image: postgres:latest
    container_name: auth-service-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5001:5432"
    volumes:
      - ./auth-service/auth-service-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  auth-service:
    image: auth-service:latest
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_PROFILES_ACTIVE: dev
      # gRPC clients use discovery:/// via Eureka — no static host/port needed
    depends_on:
      auth-service-db:
        condition: service_healthy
      patient-service:
        condition: service_started
      hospital-service:
        condition: service_started
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:5000"
    networks:
      - internal

  # PostgreSQL for hospital-service
  hospital-service-db:
    image: postgres:latest
    container_name: hospital-service-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5002:5432"
    volumes:
      - ./hospital-service/hospital-service-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # Hospital Service
  hospital-service:
    image: hospital-service:latest
    build:
      context: ./hospital-service
      dockerfile: Dockerfile
    container_name: hospital-service
    ports:
      - "4003:4003"
      - "9003:9003"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://hospital-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    depends_on:
      hospital-service-db:
        condition: service_healthy
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:5000"
    networks:
      - internal

  # PostgreSQL for clinical-service
  clinical-service-db:
    image: postgres:latest
    container_name: clinical-service-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5004:5432"
    volumes:
      - ./clinical-service/clinical-service-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # Clinical Service
  clinical-service:
    image: clinical-service:latest
    build:
      context: ./clinical-service
      dockerfile: Dockerfile
    container_name: clinical-service
    ports:
      - "4010:4010"
    volumes:
      - ./clinical-service/pdf-storage:/app/pdf-storage
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://clinical-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    depends_on:
      clinical-service-db:
        condition: service_healthy
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:5000"
    networks:
      - internal

  # PostgreSQL for schedule-service
  schedule-service-db:
    image: postgres:latest
    container_name: schedule-service-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5003:5432"
    volumes:
      - ./schedule-service/schedule-service-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # Schedule Service
  schedule-service:
    image: schedule-service:latest
    build:
      context: ./schedule-service
      dockerfile: Dockerfile
    container_name: schedule-service
    ports:
      - "4009:4009"
      - "9009:9009"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://schedule-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      schedule-service-db:
        condition: service_healthy
      kafka:
        condition: service_started
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:5000"
    networks:
      - internal

  notification-service-db:
    image: postgres:latest
    container_name: notification-service-db
    ports:
      - "5014:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    volumes:
      - ./notification-service/notification-service-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  notification-service:
    image: notification-service:latest
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    restart: unless-stopped
    ports:
      - "4014:4014"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://notification-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATA_REDIS_HOST: redis
    depends_on:
      notification-service-db:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:5000"
    networks:
      - internal

  zipkin:
    image: openzipkin/zipkin:3.4.2
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    networks:
      - internal

  prometheus:
    image: prom/prometheus:latest
    container_name: Prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml
    depends_on:
      - alertmanager
    networks:
      - internal

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    networks:
      - internal

  grafana:
    image: grafana/grafana:latest
    container_name: Grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    depends_on:
      - prometheus
    networks:
      - internal

  loki:
    image: grafana/loki:latest
    container_name: Loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - internal

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - internal

  elasticsearch:
    image: elasticsearch:8.14.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  logstash:
    image: logstash:8.14.0
    container_name: logstash
    ports:
      - "5000:5000"
      - "5000:5000/udp"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeling
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - internal
  kibana:
    image: kibana:8.14.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - internal

volumes:
  grafana_data:
  prometheus_data:
  elasticsearch_data:

networks:
  internal:
    external: true
