spring.application.name=billing-service

server.port=4001
grpc.server.port=9001

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://eureka:password@eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.metadata-map.gRPC_port=${grpc.server.port}

management.endpoints.web.exposure.include=health, prometheus, info
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

#open telemetry
otel.service.name=${spring.application.name}
otel.traces.exporter=zipkin
otel.exporter.zipkin.endpoint=http://zipkin:9411/api/v2/spans
otel.propagation.type=w3c
otel.instrumentation.kafka.enabled=true
otel.instrumentation.grpc.enabled=true
otel.instrumentation.logback-mdc.enabled=true
otel.logs.exporter=none

logging.structured.format.console=logstash
logging.structured.logstash.mdc-fields-include=trace_id,span_id,trace_flags