package com.pms.notificationservice.config;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class MetricsConfig {

    @Bean
    public Counter notificationSentCounter(MeterRegistry registry) {
        return Counter.builder("notifications.sent")
                .description("Notifications sent by type and channel")
                .tag("type", "all")
                .tag("channel", "all")
                .register(registry);
    }

    @Bean
    public Counter notificationFailedCounter(MeterRegistry registry) {
        return Counter.builder("notifications.failed")
                .description("Notifications that failed after 3 retries")
                .register(registry);
    }

    @Bean
    public Counter otpGeneratedCounter(MeterRegistry registry) {
        return Counter.builder("otp.generated")
                .description("OTP generated by type and channel")
                .register(registry);
    }

    @Bean
    public Counter otpVerifiedCounter(MeterRegistry registry) {
        return Counter.builder("otp.verified")
                .description("OTP codes successfully verified")
                .register(registry);
    }

    @Bean
    public Counter otpFailedCounter(MeterRegistry registry) {
        return Counter.builder("otp.failed")
                .description("OTP verification failures by reason")
                .tag("reason", "all")
                .register(registry);
    }

    @Bean
    public Counter dedupHitCounter(MeterRegistry registry) {
        return Counter.builder("redis.dedup.hit")
                .description("Duplicate notification suppressed via Redis SETNX")
                .register(registry);
    }

    @Bean
    public Counter dedupMissCounter(MeterRegistry registry) {
        return Counter.builder("redis.dedup.miss")
                .description("Duplicate notification proceeding past dedup check")
                .register(registry);
    }
}
