spring.application.name=patient-service

#in memory db outside of docker
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#
#spring.h2.console.settings.web-allow-others=true
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
##detects changes
#spring.jpa.hibernate.ddl-auto=update
##does checks
#spring.sql.init.mode=always

server.port=4000
spring.jpa.defer-datasource-initialization=true

logging.level.root=info

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

#kafka properties
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

# Same JWT secret as auth-service
jwt.secret=${JWT_SECRET}
