server:
  port: 8761

spring:
  application:
    name: eureka-server
  security:
    user:
      name: eureka
      password: password

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka:password@eureka-server:8761/eureka/
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.85

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
